### ISSUE TITLE
Popup > Update Style

### ISSUE THREAD

**Issue by Minh-Odinland** [khoipro/odinland.vn#91]
![image](https://user-images.githubusercontent.com/54342466/64965990-2d810600-d8c8-11e9-9c47-aeb5c1ae7540.png)

**Comment by khoipro** [comment]
@Minh-Odinland 

1. Phần popup này là của bên thứ ba, là 1 plugin cài vào. Nên các chỉnh sửa tiếp theo sẽ cần tính phí. Trong phần thống nhất của nội dung trước đây cũng ghi rõ là "Cấu hình và cài đặt popup plugin", không có mục nào ghi "Thay đổi, cập nhật style plugin" nên đây là hạng mục phát sinh.

2. Anh vui lòng cho demo popup nào anh nghĩ là đẹp để bên em báo giá bổ sung, chi phí ~100,000đ.
